mdapi_output_dir/objects/DailyTracker__c.object
<CustomObject>
    <label>DailyTracker</label>
    <nameField>
        <label>DailyTracker Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Actual_Test_Cases__c</fullName>
        <label>Actual Test Cases</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan_Test_Cases__c</fullName>
        <label>Plan Test Cases</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TaskName__c</fullName>
        <label>TaskName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TestDailyTrackUtil.cls
@isTest
public class TestDailyTrackUtil {
    static testMethod void validateDailyTrack() {
        Integer i = 0;
        i++;
        DailyTracker__c b = new DailyTracker__c(TaskName__c = 'Test' + i, Actual_Test_Cases__c=30);
        System.debug('Task Name is: ' + b.TaskName__c);

        //insert a dailytracker
        insert b;

        //retrieve the new daily tracker
        DailyTracker__c c = [SELECT TaskName__c, Plan_Test_Cases__c FROM DailyTracker__c WHERE Id = :b.Id];
        System.debug('c Task Name is: ' + c.TaskName__c);
        System.debug('Plan test cases is: ' + c.Plan_Test_Cases__c);

        //compare
        System.assertEquals(18, c.Plan_Test_Cases__c);

    }

}